### ISSUE TITLE
listen() method signature and implementation do not match

### ISSUE THREAD

**Issue by nazar-pc** [webtorrent/bittorrent-dht#162]
[API docs](https://github.com/webtorrent/bittorrent-dht#dhtlistenport-address-onlistening) say:
```
dht.listen([port], [address], [onlistening])
```
While [actual implementation](https://github.com/webtorrent/bittorrent-dht/blob/v7.5.3/client.js#L355) doesn't support address:
```
DHT.prototype.listen = function (port, cb) {
  if (typeof port === 'function') return this.listen(0, port)
  this._rpc.bind(port, cb)
}
```
Which is turn seems to be limited by [k-rpc](https://github.com/mafintosh/k-rpc/blob/49ea9f20eda27300c1774c30da9d06f1d9ef7387/index.js#L103) and k-rpc-socket:
```
RPC.prototype.bind = function (port, cb) {
  this.socket.bind(port, cb)
}
```

@feross and @mafintosh, could you take a look at this and add actual address support? There is nothing in k-rpc-socket that prevents this from happening.

**Comment by feross** [comment]
Good catch. I think we forgot to support the `address` param when @mafintosh refactored this to use `k-rpc` and `k-rpc-socket`. It's easy to support.

PRs out: https://github.com/mafintosh/k-rpc-socket/pull/13 https://github.com/mafintosh/k-rpc/pull/10 https://github.com/webtorrent/bittorrent-dht/pull/166
