### ISSUE TITLE
mutable put request: wrong test seq !== cas

### ISSUE THREAD

**Issue by mh-cbon** [webtorrent/bittorrent-dht#169]
hi @feross 

at https://github.com/webtorrent/bittorrent-dht/blob/master/client.js#L503

small mistake in,
```js
    var prev = this._values.get(keyHex)
    if (prev && typeof a.cas === 'number' && prev.seq !== a.cas) { // <--------here
      return this._rpc.error(peer, query, [301, 'CAS mismatch, re-read and try again'])
    }
    if (prev && typeof prev.seq === 'number' && !(a.seq > prev.seq)) {
      return this._rpc.error(peer, query, [302, 'sequence number less than current'])
}
```

Should be `prev.cas !== a.cas`

**Comment by chr15m** [comment]
@mh-cbon I don't think so. The point of the compare-and-set is to supply an index (`a.cas`) that you expect the previous `seq` to match. The code looks right to me.

**Comment by mh-cbon** [comment]
yeah, right,

> The cas field is optional. If present it specifies the sequence number of the data blob being overwritten by the put. When present, the storing node MUST compare this number to the current sequence number it has stored under this key. Only if the cas matches the stored sequence number is the put performed. If it mismatches, the store fails and an error MUST be returned. See Errors below.

sorry for that
