### ISSUE TITLE
Can I set ROTATE_INTERVAL param?

### ISSUE THREAD

**Issue by zhenlovezhen2012** [webtorrent/bittorrent-dht#187]
Can I set ROTATE_INTERVAL param? 5 minutes is to long.

Why are not allowed to set this parameter？

**Comment by mafintosh** [comment]
What's your use case for lowering it?

**Comment by feross** [comment]
Closing due to no response from issue opener.

**Comment by oleiba** [comment]
Hey, I have a use case for this.
I have an application where I set some protocol where downloaders download first, and then a bit later (like 1 minute later) uploaders seed.
For some reason, the downloaders miss the initial seeding by the uploader.
Empirically, I saw that they manage to download the data exactly after the LRU refresh, which is the ROTATE_INTERVAL, meaning after 5 minutes.
Being able to change that would be perfect for my purposes, for faster download without a long delay.
