### ISSUE TITLE
When bucket gets full send ping to old nodes, per spec

### ISSUE THREAD

**Issue by feross** [webtorrent/bittorrent-dht#20]
Use the `k-bucket` ping event,.

**Comment by feross** [comment]
@mafintosh We're not following this part of the spec, are we?

**Comment by robertkowalski** [comment]
i can confirm that bittorrent-dht doesn't follow the spec here, we run into that issue with long running production deploys (ca. 30 nodes running)

we implemented a fix and its running smooth for us: https://github.com/webtorrent/bittorrent-dht/pull/172

**Comment by feross** [comment]
This was fixed by https://github.com/webtorrent/bittorrent-dht/pull/172
