### ISSUE TITLE
Node discovery via DHT

### ISSUE THREAD

**Issue by cuiyi0326** [webtorrent/bittorrent-dht#213]
Suppose I have a few nodes on the public Internet and they don't know each other in ahead of time, what's the best way for the to discover each other (e.g., find each other's IP) via DHT?

In my current design, I'll let all of them compute a same secret hash according to some rules and announce it. When they lookup the hash, I assume they can find other nodes as peers since they announced this hash. Would this design work?

**Comment by feross** [comment]
That sounds like it would work.
