### ISSUE TITLE
dht announce

### ISSUE THREAD

**Issue by i-coderdev** [webtorrent/bittorrent-dht#214]
No dht results found 
##

const DHT = require('bittorrent-dht');

const dht = new DHT({
	host: true,
	bootstrap: [
		'router.bittorrent.com:6881',
		'router.utorrent.com:6881',
		'dht.transmissionbt.com:6881'
	]
});

dht.listen(20000, () => console.log(`Torrent dht now up and running.`));

dht.on('announce', (peer, infoHash) => {
	console.log(peer, infoHash)
});

##

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
